### ISSUE TITLE
ROUND_ROBIN balancing strategy: make it production ready

### ISSUE THREAD

**Issue by jibon57** [bigbluebutton/bbb-webrtc-sfu#65]
Hello,

I was trying to add 2 external `kurento` servers like this way:

```
- ip: External_IP_1
  url: ws://External_IP_1:8888/kurento
  # mediaType: (main|audio|content)
  ipClassMappings:
    local:
    private:
    public:
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
- ip: External_IP_2
  url: ws://External_IP_2:8888/kurento
  # mediaType: (main|audio|content)
  ipClassMappings:
    local:
    private:
    public:
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
```
And `balancing-strategy: ROUND_ROBIN`
But I saw `bbb-webrtc-sfu` was selecting first server only. It wasn't select second one. Am I following correctly? Please help to find in where I'm doing mistake. 

Log:
```
2020-09-28T09:45:47.359Z - info: [mcs-freeswitch-esl-wrapper] Connected to FreeSWITCH ESL
2020-09-28T09:45:47.369Z - info: [mcs-balancer] Available hosts => [{"url":"ws://External_IP_1:8888/kurento","ip":"External_IP_1","mediaType":"all"}]
2020-09-28T09:45:47.371Z - info: [mcs-balancer] Available hosts => [{"url":"ws://External_IP_1:8888/kurento","ip":"External_IP_1","mediaType":"all"},{"url":"ws://External_IP_2:8888/kurento","ip":"External_IP_2","mediaType":"all"}]

```
Thanks

**Comment by jibon57** [comment]
I think I've found the reason: https://github.com/bigbluebutton/bbb-webrtc-sfu/blob/6b26493b0c17bca2b667779b8498abeb66310b3c/lib/mcs-core/lib/media/balancer.js#L181
May be it's because it's wait until it cross `video-transposing-ceiling` & `audio-transposing-ceiling` value.

**Comment by prlanzarin** [comment]
>  May be it's because it's wait until it cross video-transposing-ceiling & audio-transposing-ceiling value.

That's correct. It does a round-robin based on the configured thresholds. As it is now, it puts every media (inbound or outbound) into the round robin scheme following the configured *-ceilings. If there's a host mismatch between medias (eg subscriber media X is on KMS 1, publisher media Y is on KMS 2), a RTP bridge is done between KMS 1 and 2 to connect Y to X.

I don't recommend using ROUND_ROBIN in production yet, though. It's in an experimental state and has problems with unintended transcoding due to how medias are transposed between Kurento instances. And the transposing is currently on plain RTP, so medias are not DTLS-SRTP encrypted.

You're better off with MEDIA_TYPE for the time being. I plan on reviewing the ROUND_ROBIN strategy soon. I'll probably make it simpler: a true, naive **inbound** media round robin. That will make it usable and easier to maintain.

**Comment by jibon57** [comment]
Thanks for your response @prlanzarin . Can I use multiple KMS servers as `MEDIA_TYPE`? For example: Server 1 & Server 2 for webcams only:

```
- ip: External_IP_1
  url: ws://External_IP_1:8888/kurento
  mediaType: main
  ipClassMappings:
    local:
    private:
    public:
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
- ip: External_IP_2
  url: ws://External_IP_2:8888/kurento
  mediaType: main
  ipClassMappings:
    local:
    private:
    public:
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
- ip: External_IP_3
  url: ws://External_IP_2:8888/kurento
  mediaType: audio
  ipClassMappings:
    local:
    private:
    public:
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
- ip: External_IP_3
  url: ws://External_IP_2:8888/kurento
  mediaType: content
  ipClassMappings:
    local:
    private:
    public:
  options:
    failAfter: 5
    request_timeout: 30000
    response_timeout: 30000
kurentoStartupRetries: 10
balancing-strategy: MEDIA_TYPE
video-transposing-ceiling: 1
audio-transposing-ceiling: 1
```
Is that correct way to setup?
